# Header
menu:
  首页: /
  归档: /archives
  随笔: /tags/随笔
  相册: photo

# SubNav
subnav:
  github: "https://github.com/lwzhang"
  weibo: "http://weibo.com/u/1684901103/home?wvr=5"
  rss: "/atom.xml"
  zhihu: "#" 
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.jpg

#你的头像url
avatar: /assets/blogImg/avatar1.jpg
#是否开启分享
#share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  张鑫旭: http://www.zhangxinxu.com/wordpress/category/js/
  小胡子哥: http://barretlee.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我有一只小毛驴，我从来也不骑。有一天我心血来潮骑着去赶集。我手里拿着小皮鞭我心里正得意。不知怎么哗啦啦啦啦啦，我摔了一身泥
